// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void test() {
    driver.get("https://opensource-demo.orangehrmlive.com/web/index.php/auth/login");
    driver.manage().window().setSize(new Dimension(1621, 1025));
    driver.findElement(By.name("username")).sendKeys("Admin");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("admin123");
    driver.findElement(By.cssSelector(".oxd-button")).click();
    driver.findElement(By.linkText("My Info")).click();
    driver.findElement(By.xpath("//div[2]/div/div/div/div[2]/input")).click();
    driver.findElement(By.cssSelector(".oxd-input--focus")).sendKeys("53535335");
    driver.findElement(By.cssSelector(".oxd-input--focus")).click();
    driver.findElement(By.cssSelector(".oxd-input--focus")).click();
    driver.findElement(By.cssSelector(".oxd-input--focus")).sendKeys("5365277");
    driver.findElement(By.cssSelector(".oxd-button--secondary:nth-child(2)")).click();
    driver.findElement(By.xpath("//div[2]/div/div/div/div[2]/input")).click();
    {
      String value = driver.findElement(By.cssSelector(".oxd-input--focus")).getAttribute("value");
      assertThat(value, is("5365277"));
    }
    driver.findElement(By.xpath("//div[2]/div/div/div/div[2]/input")).click();
    {
      String value = driver.findElement(By.cssSelector(".oxd-input--focus")).getAttribute("value");
      assertThat(value, is("5365277"));
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".oxd-button--secondary:nth-child(2)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".oxd-main-menu-item-wrapper:nth-child(8) .oxd-text")).click();
    {
      WebElement element = driver.findElement(By.linkText("Dashboard"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".oxd-userdropdown-name")).click();
    driver.findElement(By.linkText("Logout")).click();
    driver.close();
  }
}
